// Copyright CVOYA LLC. Licensed under the Business Source License 1.1.
// See LICENSE.md in the project root for full license terms.

namespace Cvoya.Spring.Connector.Slack.Install;

using System;
using System.Collections.Generic;

using Cvoya.Spring.Connector.Slack.Provisioning;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

/// <summary>
/// Maps <c>POST /api/v1/tenant/connectors/slack/install</c> onto the
/// route group the platform pre-scopes for the Slack connector (#2882).
/// The endpoint is the portal wizard's server-side equivalent of the
/// <c>spring connector slack install --write-tenant-secrets</c> CLI verb:
/// it provisions a Slack app via the Manifest API, persists the OAuth
/// credentials as tenant secrets, and returns a state-bearing consent URL
/// the portal opens in the OAuth popup.
///
/// <para>
/// One request shape drives both the wizard's "preview manifest" action
/// (<c>dryRun: true</c> — returns the manifest JSON, no network /
/// persistence) and the "install" action (<c>dryRun: false</c> — the full
/// validate → create → persist → authorize flow).
/// </para>
/// </summary>
public static class SlackInstallEndpoints
{
    /// <summary>Registers the <c>install</c> endpoint on the supplied builder.</summary>
    public static void MapSlackInstallEndpoints(this IEndpointRouteBuilder group)
    {
        group.MapPost("/install", InstallAsync)
            .WithName("InstallSlackApp")
            .WithSummary("Provision a Slack app via the Manifest API and return its OAuth consent URL")
            .WithTags("Connectors.Slack")
            .Accepts<SlackInstallRequest>("application/json")
            .Produces<SlackInstallResponse>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status502BadGateway);

        group.MapGet("/install/status", InstallStatusAsync)
            .WithName("GetSlackInstallStatus")
            .WithSummary("Report whether Slack OAuth credentials are already configured for this tenant")
            .WithTags("Connectors.Slack")
            .Produces<SlackInstallStatusResponse>(StatusCodes.Status200OK);
    }

    private static async Task<IResult> InstallStatusAsync(
        [FromServices] ISlackManifestInstallService service,
        CancellationToken cancellationToken)
    {
        var configured = await service.IsOAuthConfiguredAsync(cancellationToken);
        return Results.Ok(new SlackInstallStatusResponse(configured));
    }

    private static async Task<IResult> InstallAsync(
        [FromBody] SlackInstallRequest? request,
        [FromServices] ISlackManifestInstallService service,
        HttpContext httpContext,
        CancellationToken cancellationToken)
    {
        request ??= new SlackInstallRequest(null, null, null, false, false, null);

        var appName = string.IsNullOrWhiteSpace(request.AppName)
            ? "Spring Voyage"
            : request.AppName!.Trim();
        var svHost = ResolveSvHost(request.SvHost, httpContext);

        if (!IsValidHost(svHost))
        {
            return Results.Problem(
                title: "Invalid Spring Voyage host",
                detail: $"'{svHost}' must be an absolute http(s) URL. Set the Spring Voyage host field " +
                        "to the public base URL Slack will call (e.g. https://sv.example.com).",
                statusCode: StatusCodes.Status400BadRequest);
        }

        // The config token can only be omitted on a manifest-preview
        // (dry-run) request; a real install needs it to call Slack.
        if (!request.DryRun && string.IsNullOrWhiteSpace(request.ConfigToken))
        {
            return Results.Problem(
                title: "Missing Slack configuration token",
                detail: "Paste a Slack Configuration Token (generated by a workspace admin on " +
                        "Settings → Your Apps → 'Generate Configuration Tokens') before installing.",
                statusCode: StatusCodes.Status400BadRequest);
        }

        try
        {
            var result = await service.InstallAsync(
                new SlackManifestInstallRequest(
                    ConfigToken: request.ConfigToken,
                    AppName: appName,
                    SvHost: svHost,
                    SocketMode: request.SocketMode,
                    DryRun: request.DryRun,
                    ClientState: request.ClientState),
                cancellationToken);

            return Results.Ok(new SlackInstallResponse(
                ManifestJson: result.ManifestJson,
                DryRun: result.DryRun,
                AppId: result.AppId,
                AuthorizeUrl: result.AuthorizeUrl,
                State: result.State,
                WrittenSecretNames: result.WrittenSecretNames));
        }
        catch (SlackManifestException ex)
        {
            // Slack rejected the manifest validate / create. Surface the
            // structured Slack error code under `code` so the wizard can
            // special-case an expired token (invalid_auth) the same way
            // the rest of the portal reads ProblemDetails extensions.
            return Results.Problem(
                title: "Slack rejected the app manifest",
                detail: BuildSlackErrorDetail(ex),
                statusCode: StatusCodes.Status502BadGateway,
                extensions: new Dictionary<string, object?>
                {
                    ["code"] = string.IsNullOrWhiteSpace(ex.ErrorCode) ? "slack_error" : ex.ErrorCode,
                });
        }
        catch (InvalidOperationException ex)
        {
            // BeginAuthorization couldn't resolve OAuth config after the
            // write — surfaced via the same 502 shape the OAuth authorize
            // endpoint uses for the not-configured case.
            return Results.Problem(
                title: "Slack OAuth is not configured",
                detail: ex.Message,
                statusCode: StatusCodes.Status502BadGateway);
        }
    }

    /// <summary>
    /// Resolves the Spring Voyage host the manifest embeds. Prefers the
    /// operator-supplied value; falls back to the public base URL this
    /// request arrived on (scheme + host, honouring forwarded headers when
    /// the host configures them).
    /// </summary>
    private static string ResolveSvHost(string? supplied, HttpContext httpContext)
    {
        if (!string.IsNullOrWhiteSpace(supplied))
        {
            return supplied.Trim();
        }

        var request = httpContext.Request;
        return $"{request.Scheme}://{request.Host.Value}";
    }

    private static bool IsValidHost(string host) =>
        Uri.TryCreate(host, UriKind.Absolute, out var uri)
        && (uri.Scheme == Uri.UriSchemeHttp || uri.Scheme == Uri.UriSchemeHttps);

    private static string BuildSlackErrorDetail(SlackManifestException ex)
    {
        var code = string.IsNullOrWhiteSpace(ex.ErrorCode) ? "unknown_error" : ex.ErrorCode;
        return code switch
        {
            "invalid_auth" or "not_authed" or "token_expired" or "token_revoked" or "account_inactive" =>
                $"Slack rejected the configuration token ({code}). Configuration Tokens are short-lived " +
                "(~12h) — generate a fresh one from your workspace admin's 'Your Apps' page and retry.",
            "invalid_manifest" =>
                "Slack rejected the generated manifest. This usually means the app name is already taken " +
                "in the workspace — try a different name.",
            "name_taken" =>
                "That Slack app name is already taken in the workspace. Choose a different app name and retry.",
            _ => $"Slack returned error '{code}'. {ex.Message}",
        };
    }
}

/// <summary>Request body for <c>POST /install</c>.</summary>
/// <param name="ConfigToken">
/// The Slack Configuration Token. Required for a real install; may be
/// omitted on a <see cref="DryRun"/> manifest preview.
/// </param>
/// <param name="AppName">Display name for the new Slack app. Defaults to "Spring Voyage" when blank.</param>
/// <param name="SvHost">
/// Override the Spring Voyage base URL baked into the manifest. When blank
/// the server uses the public base URL the request arrived on.
/// </param>
/// <param name="SocketMode">Generate the manifest with Socket Mode enabled (local-dev installs).</param>
/// <param name="DryRun">Build + return the manifest without contacting Slack or persisting anything.</param>
/// <param name="ClientState">
/// Opaque state echoed through the OAuth handoff (the portal's
/// <c>targetOrigin</c>), so the callback can <c>postMessage</c> the
/// outcome back to the right origin.
/// </param>
public record SlackInstallRequest(
    string? ConfigToken,
    string? AppName,
    string? SvHost,
    bool SocketMode,
    bool DryRun,
    string? ClientState);

/// <summary>Response body for <c>POST /install</c>.</summary>
/// <param name="ManifestJson">The manifest JSON sent to Slack — the wizard renders it as a preview.</param>
/// <param name="DryRun">Whether this was a preview-only request.</param>
/// <param name="AppId">The new Slack app id (null on a dry-run).</param>
/// <param name="AuthorizeUrl">The state-bearing Slack consent URL to open in the OAuth popup (null on a dry-run).</param>
/// <param name="State">The OAuth state token (surfaced for debugging; never secret — null on a dry-run).</param>
/// <param name="WrittenSecretNames">The tenant-secret names persisted (empty on a dry-run).</param>
public record SlackInstallResponse(
    string ManifestJson,
    bool DryRun,
    string? AppId,
    string? AuthorizeUrl,
    string? State,
    IReadOnlyList<string> WrittenSecretNames);

/// <summary>Response body for <c>GET /install/status</c>.</summary>
/// <param name="OauthConfigured">
/// <c>true</c> when a complete set of Slack OAuth credentials (client id,
/// client secret, signing secret, redirect uri) already resolves for this
/// tenant — i.e. the operator can connect to Slack without registering a
/// new app. The wizard uses this to offer the "connect now" shortcut.
/// </param>
public record SlackInstallStatusResponse(bool OauthConfigured);
