// <auto-generated />
using System;
using System.Text.Json;
using Cvoya.Spring.Dapr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cvoya.Spring.Dapr.Data.Migrations
{
    [DbContext(typeof(SpringDbContext))]
    [Migration("20260510082058_AddCloningPolicies")]
    partial class AddCloningPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spring")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cvoya.Spring.Dapr.Costs.CostRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("cost");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Work")
                        .HasColumnName("source");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UnitId");

                    b.ToTable("cost_records", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.ActivityEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cost");

                    b.Property<JsonElement?>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.ToTable("activity_events", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.AgentDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<JsonElement?>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("agent_definitions", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.AgentExpertiseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InputSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("input_schema_json");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AgentId")
                        .HasDatabaseName("ix_agent_expertise_tenant_agent");

                    b.HasIndex("TenantId", "AgentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_expertise_tenant_agent_name");

                    b.ToTable("agent_expertise", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.AgentLiveConfigEntity", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int>("ExecutionMode")
                        .HasColumnType("integer")
                        .HasColumnName("execution_mode");

                    b.Property<bool>("ExpertiseInitialised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("expertise_initialised");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<string>("Specialty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("specialty");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AgentId");

                    b.HasIndex("TenantId");

                    b.ToTable("agent_live_config", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.AgentSkillGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("skill_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AgentId")
                        .HasDatabaseName("ix_agent_skill_grants_tenant_agent");

                    b.HasIndex("TenantId", "AgentId", "SkillName")
                        .IsUnique()
                        .HasDatabaseName("ux_agent_skill_grants_tenant_agent_skill");

                    b.ToTable("agent_skill_grants", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.ApiTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("scopes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("api_tokens", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.BudgetLimitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DailyBudget")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("daily_budget");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ScopeType")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_limits_tenant_scope_null")
                        .HasFilter("scope_id IS NULL");

                    b.HasIndex("TenantId", "ScopeType", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_limits_tenant_scope")
                        .HasFilter("scope_id IS NOT NULL");

                    b.ToTable("budget_limits", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.CloningPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement>("Policy")
                        .HasColumnType("jsonb")
                        .HasColumnName("policy");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ScopeType")
                        .IsUnique()
                        .HasDatabaseName("ix_cloning_policies_tenant_scope_null")
                        .HasFilter("scope_id IS NULL");

                    b.HasIndex("TenantId", "ScopeType", "ScopeId")
                        .IsUnique()
                        .HasDatabaseName("ix_cloning_policies_tenant_scope")
                        .HasFilter("scope_id IS NOT NULL");

                    b.ToTable("cloning_policies", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.ConnectorDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement?>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("InstallState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("install_state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("connector_definitions", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.CredentialHealthEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SecretName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret_name");

                    b.Property<DateTimeOffset>("LastChecked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("TenantId", "Kind", "SubjectId", "SecretName");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Kind");

                    b.ToTable("credential_health", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.HumanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email");

                    b.Property<string>("NotificationPreferences")
                        .HasColumnType("jsonb")
                        .HasColumnName("notification_preferences");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("humans", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("RecipientScheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recipient_scheme");

                    b.Property<DateTimeOffset?>("RetractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retracted_at");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderScheme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sender_scheme");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("TenantId", "ThreadId", "SentAt")
                        .HasDatabaseName("ix_messages_tenant_thread_sent_at");

                    b.ToTable("messages", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.PackageInstallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("inputs_json");

                    b.Property<Guid>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("OriginalManifestYaml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_manifest_yaml");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("package_name");

                    b.Property<string>("PackageRoot")
                        .HasColumnType("text")
                        .HasColumnName("package_root");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "InstallId");

                    b.ToTable("package_installs", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.SecretRegistryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<bool>("Propagate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("propagate");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<string>("StoreKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("store_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Scope", "OwnerId", "Name")
                        .HasDatabaseName("ix_secret_registry_tenant_scope_owner_name");

                    b.HasIndex("TenantId", "Scope", "OwnerId", "Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_secret_registry_tenant_scope_owner_name_version");

                    b.ToTable("secret_registry_entries", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.TenantConnectorInstallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement?>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<string>("ConnectorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("connector_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<Guid?>("PackageInstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_install_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ConnectorId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_connector_installs_tenant_slug")
                        .HasFilter("\"package_install_id\" IS NULL AND \"unit_id\" IS NULL");

                    b.HasIndex("TenantId", "ConnectorId", "PackageInstallId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_connector_installs_pkg_scope")
                        .HasFilter("\"package_install_id\" IS NOT NULL AND \"unit_id\" IS NULL");

                    b.HasIndex("TenantId", "ConnectorId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_connector_installs_unit_scope")
                        .HasFilter("\"unit_id\" IS NOT NULL");

                    b.ToTable("tenant_connector_installs", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.TenantModelProviderInstallEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_id");

                    b.Property<JsonElement?>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "ProviderId");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_model_provider_installs", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.TenantRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tenants", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.TenantSkillBundleBindingEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("BundleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("bundle_id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid?>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("InstallState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("install_state");

                    b.HasKey("TenantId", "BundleId");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_skill_bundle_bindings", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.ThreadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("ParticipantKey")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("participant_key");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("participants");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ParticipantKey")
                        .IsUnique()
                        .HasDatabaseName("ux_threads_tenant_participant_key");

                    b.ToTable("threads", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitConnectorBindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bound_at");

                    b.Property<JsonElement>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<Guid>("ConnectorType")
                        .HasColumnType("uuid")
                        .HasColumnName("connector_type");

                    b.Property<JsonElement?>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ConnectorType")
                        .HasDatabaseName("ix_unit_connector_bindings_tenant_type");

                    b.HasIndex("TenantId", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ux_unit_connector_bindings_tenant_unit");

                    b.ToTable("unit_connector_bindings", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement?>("Definition")
                        .HasColumnType("jsonb")
                        .HasColumnName("definition");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("InstallId")
                        .HasColumnType("uuid")
                        .HasColumnName("install_id");

                    b.Property<string>("InstallState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("install_state");

                    b.Property<string>("LastValidationErrorJson")
                        .HasColumnType("text")
                        .HasColumnName("last_validation_error_json");

                    b.Property<string>("LastValidationRunId")
                        .HasColumnType("text")
                        .HasColumnName("last_validation_run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("unit_definitions", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitExpertiseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InputSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("input_schema_json");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UnitId")
                        .HasDatabaseName("ix_unit_expertise_tenant_unit");

                    b.HasIndex("TenantId", "UnitId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_unit_expertise_tenant_unit_name");

                    b.ToTable("unit_expertise", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitHumanPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("HumanId")
                        .HasColumnType("uuid")
                        .HasColumnName("human_id");

                    b.Property<string>("Identity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("identity");

                    b.Property<bool>("Notifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("permission_level");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UnitId", "HumanId")
                        .IsUnique()
                        .HasDatabaseName("ux_unit_human_permissions_tenant_unit_human");

                    b.ToTable("unit_human_permissions", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitLiveConfigEntity", b =>
                {
                    b.Property<Guid>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<JsonElement?>("Boundary")
                        .HasColumnType("jsonb")
                        .HasColumnName("boundary");

                    b.Property<string>("Color")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("color");

                    b.Property<bool>("ExpertiseInitialised")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("expertise_initialised");

                    b.Property<string>("Hosting")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hosting");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<int>("PermissionInheritance")
                        .HasColumnType("integer")
                        .HasColumnName("permission_inheritance");

                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UnitId");

                    b.HasIndex("TenantId");

                    b.ToTable("unit_live_config", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitMembershipEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<int?>("ExecutionMode")
                        .HasColumnType("integer")
                        .HasColumnName("execution_mode");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<string>("Specialty")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("specialty");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "UnitId", "AgentId");

                    b.HasIndex("TenantId", "AgentId")
                        .HasDatabaseName("ix_unit_memberships_tenant_agent_id");

                    b.ToTable("unit_memberships", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitPolicyEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<JsonElement?>("Cost")
                        .HasColumnType("jsonb")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonElement?>("ExecutionMode")
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_mode");

                    b.Property<JsonElement?>("Initiative")
                        .HasColumnType("jsonb")
                        .HasColumnName("initiative");

                    b.Property<JsonElement?>("Model")
                        .HasColumnType("jsonb")
                        .HasColumnName("model");

                    b.Property<JsonElement?>("Skill")
                        .HasColumnType("jsonb")
                        .HasColumnName("skill");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "UnitId");

                    b.ToTable("unit_policies", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.UnitSubunitMembershipEntity", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "ParentId", "ChildId");

                    b.HasIndex("TenantId", "ChildId")
                        .HasDatabaseName("ix_unit_subunit_memberships_tenant_child");

                    b.ToTable("unit_subunit_memberships", "spring");
                });

            modelBuilder.Entity("Cvoya.Spring.Dapr.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("Cvoya.Spring.Dapr.Data.Entities.ThreadEntity", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_thread_id");
                });
#pragma warning restore 612, 618
        }
    }
}
