// Copyright CVOYA LLC. Licensed under the Business Source License 1.1.
// See LICENSE.md in the project root for full license terms.

namespace Cvoya.Spring.Dapr.Tests.Prompts;

using System.Text.Json;

using Cvoya.Spring.Core.Skills;
using Cvoya.Spring.Dapr.Prompts;

using Shouldly;

using Xunit;

/// <summary>
/// Unit tests for <see cref="UnitContextBuilder"/>. The peer-directory
/// rendering tested here pre-#2231 was removed alongside
/// <c>PromptAssemblyContext.Members</c>; the per-registry skill listing
/// was removed in #2670 (the always-on platform-tool catalog now lives
/// in Layer 1 via <see cref="PlatformPromptProvider"/>, and connector
/// instructions ride <c>IConnectorPromptContextResolver</c> via the
/// platform-layer connector-context section).
/// </summary>
public class UnitContextBuilderTests
{
    private readonly UnitContextBuilder _builder = new();

    /// <summary>
    /// Verifies that policies are included in the output.
    /// </summary>
    [Fact]
    public void Build_IncludesPolicies()
    {
        var policies = JsonSerializer.SerializeToElement(new { maxRetries = 3, timeout = "30s" });

        var result = _builder.Build(policies);

        result.ShouldContain("Policies");
        result.ShouldContain("maxRetries");
    }

    /// <summary>
    /// Verifies that empty inputs produce an empty string.
    /// </summary>
    [Fact]
    public void Build_HandlesEmptyInputs()
    {
        var result = _builder.Build(null);

        result.ShouldBeEmpty();
    }

    /// <summary>
    /// Pins the #2670 acceptance: there is no per-registry skill
    /// catalog in Layer 2. The always-on platform-tool catalog lives
    /// in Layer 1 (<see cref="PlatformPromptProvider"/>) and connector
    /// instructions ride <c>IConnectorPromptContextResolver</c> via
    /// the platform-layer connector-context section — Layer 2 must
    /// not emit a duplicate "Available Skills" block or the
    /// auto-generated "Tools exposed by the X connector." strings.
    /// </summary>
    [Fact]
    public void Build_NeverRendersAvailableSkillsBlockOrAutoGeneratedDescriptions()
    {
        // A populated unit (policies + a bundle) is the maximal Layer 2
        // input shape; if no path can synthesise an "Available Skills"
        // heading here, none ever will.
        var policies = JsonSerializer.SerializeToElement(new { maxRetries = 3 });
        var bundles = new List<SkillBundle>
        {
            new("acme/team", "policy", "## Team Policy", Array.Empty<SkillToolRequirement>()),
        };

        var result = _builder.Build(policies, bundles);

        result.ShouldNotContain("Available Skills");
        result.ShouldNotContain("Tools exposed by the");
        result.ShouldNotContain("**sv**:");
    }

    /// <summary>
    /// Package-level skill bundles (#167) render after policies in
    /// declaration order. With the per-registry skill listing gone
    /// (#2670), the Layer 2 ordering is policies → skill bundles.
    /// </summary>
    [Fact]
    public void Build_IncludesSkillBundlesAfterPolicies_InDeclarationOrder()
    {
        var emptySchema = JsonSerializer.SerializeToElement(new { });
        var bundles = new List<SkillBundle>
        {
            new("spring-voyage/software-engineering", "triage-and-assign",
                "## Triage & Assignment\nClassify incoming work.",
                new[] { new SkillToolRequirement("platform.assign_to_agent", "assign work", emptySchema, false) }),
            new("spring-voyage/software-engineering", "pr-review-cycle",
                "## PR Review Cycle\nRoute PR reviews.",
                Array.Empty<SkillToolRequirement>()),
        };

        var policies = JsonSerializer.SerializeToElement(new { maxRetries = 3 });
        var result = _builder.Build(policies, bundles);

        result.ShouldContain("### Policies");
        result.ShouldContain("### Skill Bundles");
        result.ShouldContain("spring-voyage/software-engineering/triage-and-assign");
        result.ShouldContain("platform.assign_to_agent");
        result.ShouldContain("spring-voyage/software-engineering/pr-review-cycle");

        var policiesIdx = result.IndexOf("### Policies", StringComparison.Ordinal);
        var bundlesIdx = result.IndexOf("### Skill Bundles", StringComparison.Ordinal);
        var triageIdx = result.IndexOf("triage-and-assign", StringComparison.Ordinal);
        var reviewIdx = result.IndexOf("pr-review-cycle", StringComparison.Ordinal);

        policiesIdx.ShouldBeLessThan(bundlesIdx);
        triageIdx.ShouldBeLessThan(reviewIdx);
    }

    /// <summary>
    /// A bundle with no required tools is prompt-only — it still
    /// renders its prompt fragment but omits the "Required tools"
    /// sub-section.
    /// </summary>
    [Fact]
    public void Build_PromptOnlyBundle_OmitsRequiredToolsSubsection()
    {
        var bundles = new List<SkillBundle>
        {
            new("acme/prompt-only", "intro", "## Intro prompt", Array.Empty<SkillToolRequirement>()),
        };

        var result = _builder.Build(null, bundles);

        result.ShouldContain("## Intro prompt");
        result.ShouldNotContain("Required tools:");
    }
}
