#!/usr/bin/env bash
# PreToolUse(Edit|Write) guard: block hand edits to generated OpenAPI client types.
#
# Claude Code and Codex both pass the tool payload as JSON on stdin. The edited
# file path is `.tool_input.file_path`. Exit 2 blocks the tool call; fail open
# when jq is missing or the input is not a file-edit payload.
set -u

input="$(cat)"

if ! command -v jq >/dev/null 2>&1; then
  printf 'guard-generated-files: jq not found; guard skipped.\n' >&2
  exit 0
fi

path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)"
[ -z "$path" ] && exit 0

case "$path" in
  src/Cvoya.Spring.Web/src/lib/api/schema.d.ts|*/src/Cvoya.Spring.Web/src/lib/api/schema.d.ts)
    {
      printf 'STOP: %s is generated by openapi-typescript.\n' "$path"
      printf 'Run npm --workspace=spring-voyage-dashboard run typecheck (or the openapi-diff command/skill) instead of editing it.\n'
    } >&2
    exit 2
    ;;
esac

exit 0
